baseURL = "https://hemashushu.github.io/"
languageCode = "en-us"
copyright = "Copyright &copy; 2023 - Hippospark Young"
title = "河马蜀黍的个人主页"
theme = "hugo-selina"
publishDir = "../docs"
googleAnalytics = 'G-J7X4YJHXM9'

# English is the default language
defaultContentLanguage = "en"
# Force to have /en/page and /zh/page routes, even for default language.
# defaultContentLanguageInSubdir= true

paginate = 24

[author]
    name = "hemashushu"
    github = "hemashushu"
    twitter = "hemashushu"
    youtube = "@hemashushu"
    # gitlab = "hemashushu"

[params]
    customCSS = ["/css/custom.css"]
    mathjax = true

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = false
    lineNos = false
    lineNumbersInTable = false
    style = 'rose-pine-dawn'
    tabWidth = 4

[languages]
  [languages.zh]
    title = "河马蜀黍的个人主页"
    weight = 1
    languageName = "中文"

    # summary settings
    # https://gohugobrasil.netlify.app/content-management/summaries/
    hasCJKLanguage = true
    summaryLength = 255

    [languages.zh.params]
      tagline = "好奇、探索、创造"
      description = "河马蜀黍的个人主页，分享一些计算机知识、编程技术、学习心得，发布一些自己制作的小软件和硬件"

  [languages.en]
    title = "Hemashushu's Homepage"
    weight = 2
    languageName = "English"
    [languages.en.params]
      tagline = "Curiosity, exploration and creation"
      description = "Hemashushu's homepage, sharing some computer technology, programming skills, learning notes, some home-brew softwares and hardwares"