baseURL = 'https://hemashushu.github.io/'
languageCode = 'en-us'
copyright = "Copyright &copy; 2022 - Hippospark"
title = '河马蜀黍真是的'
theme = "hugo-kiera"
publishDir = "../docs"

[author]
    name = "hemashushu"
    github = "hemashushu"
    twitter = "hemashushu"

[params]
    tagline = "一起发现那些好玩有趣的计算机知识"
    description = "记录一些计算机基础知识、编程技术、学习心得，发布一些自己制作的小软件"
    customCSS = ["/css/custom.css"]
